[general]
pidfile="logs/burrow.pid"

[client-profile.dev]
kafka-version="0.11.0.1"
client-id="burrow-client"

[logging]
filename="logs/burrow.log"
level="info"
maxsize=100
maxbackups=30
maxage=10
use-localtime=false
use-compression=true

[zookeeper]
servers=[ "zookeeper:2181" ]
timeout=6
root-path="/burrow"

[cluster.local]
class-name="kafka"
servers=[ "kafka:9092" ]
client-profile="dev"
topic-refresh=60
offset-refresh=30

[consumer.local]
class-name="kafka"
cluster="local"
client-profile="dev"
servers=[ "kafka:9092" ]
group-blacklist="^(console-consumer-).*$"

[storage.mystorage]
class-name="inmemory"
intervals=10
expire-group=604800
workers=20
min-distance=1
group-whitelist=".*"

[notifier.slack]
class-name="http"
url-open="https://hooks.slack.com/services/xxx"
url-close="https://hooks.slack.com/services/xxx"
template-open="configs/default-slack-post.tmpl"
template-close="configs/default-slack-delete.tmpl"
send-close=true

[httpserver.default]
address=":8000"
